import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import Logout from "./logout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          {!!session && <Logout />}
          {!session && <Link href="/login">Login</Link>}
          &nbsp;
          &nbsp;
          &nbsp;
          {!session && <Link href={"/register"}>SignUp</Link>}
          &nbsp;
          &nbsp;
          &nbsp;
          {!session && <Link href={"/dashboard"}>Dashboard</Link>}
        </nav>
        {children}
      </body>
    </html>
  );
}
